import os
import re
import sqlite3
import time

from database import DATABASE_BACKEND, get_db_connection, row_to_dict
from db_utils import compute_content_hash, utc_timestamp


FTS_TABLE = "corpus_entries_fts"
POSTGRES_SEARCH_FIELDS = ("content", "title", "speaker", "current_segment", "segment_text")
POSTGRES_SEARCH_TEXT_FIELD = "search_text"
ENABLE_QUERY_TIMING = os.environ.get("ENABLE_QUERY_TIMING", "").strip().lower() in {"1", "true", "yes", "on"}
POSTGRES_FAST_SEARCH = os.environ.get("POSTGRES_FAST_SEARCH", "").strip().lower() in {"1", "true", "yes", "on"}
STORAGE_METADATA_COLUMNS = {
    "storage_backend": "TEXT DEFAULT 'local'",
    "object_key": "TEXT",
    "file_url": "TEXT",
    "file_hash": "TEXT",
}


def is_postgres():
    return DATABASE_BACKEND == "postgres"


def placeholder():
    return "%s" if is_postgres() else "?"


def close_connection(conn):
    conn.close()


def timing_log(label, start_time, **details):
    if not ENABLE_QUERY_TIMING:
        return
    detail_text = " ".join(f"{key}={value}" for key, value in details.items())
    print(f"[query_timing] {label} elapsed_ms={(time.perf_counter() - start_time) * 1000:.2f} {detail_text}", flush=True)


def timed_connection(label):
    start = time.perf_counter()
    conn = get_db_connection()
    if is_postgres():
        timing_log(f"{label}.connect", start)
    return conn


def is_missing_search_text_error(exc):
    return is_postgres() and "search_text" in str(exc).lower()


def fetch_all_dicts(cursor):
    return [row_to_dict(row) for row in cursor.fetchall()]


def fetch_one_dict(cursor):
    return row_to_dict(cursor.fetchone())


def build_search_text(*values):
    return " ".join(str(value).strip() for value in values if value is not None and str(value).strip())


def ensure_storage_metadata_columns(conn):
    table_names = ("corpus_submissions", "multimodal_entries")
    if is_postgres():
        for table_name in table_names:
            for column, column_type in STORAGE_METADATA_COLUMNS.items():
                conn.execute(f'ALTER TABLE {table_name} ADD COLUMN IF NOT EXISTS {column} {column_type}')
        return
    for table_name in table_names:
        try:
            existing = {row["name"] for row in conn.execute(f"PRAGMA table_info({table_name})").fetchall()}
            for column, column_type in STORAGE_METADATA_COLUMNS.items():
                if column not in existing:
                    conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {column} {column_type}")
        except sqlite3.OperationalError as exc:
            print(f"SQLite storage metadata migration skipped for {table_name}: {exc}", flush=True)


def has_storage_metadata_schema(conn, table_name):
    if is_postgres():
        return True
    try:
        existing = {row["name"] for row in conn.execute(f"PRAGMA table_info({table_name})").fetchall()}
    except sqlite3.OperationalError:
        return False
    return set(STORAGE_METADATA_COLUMNS).issubset(existing)


def init_submission_tables():
    conn = get_db_connection()
    try:
        if is_postgres():
            conn.execute("""
                CREATE TABLE IF NOT EXISTS corpus_submissions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    submitter_name TEXT,
                    submitter_email TEXT,
                    title TEXT NOT NULL,
                    source TEXT,
                    category TEXT NOT NULL,
                    genre TEXT,
                    language TEXT,
                    modality TEXT NOT NULL,
                    text_content TEXT,
                    original_filename TEXT,
                    stored_filename TEXT,
                    file_path TEXT,
                    file_mime_type TEXT,
                    file_size BIGINT,
                    storage_backend TEXT DEFAULT 'local',
                    object_key TEXT,
                    file_url TEXT,
                    file_hash TEXT,
                    status TEXT DEFAULT 'pending',
                    admin_note TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    reviewed_at TIMESTAMP,
                    reviewed_by TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS multimodal_entries (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    submission_id BIGINT UNIQUE,
                    title TEXT NOT NULL,
                    source TEXT,
                    category TEXT,
                    genre TEXT,
                    language TEXT,
                    modality TEXT NOT NULL,
                    text_content TEXT,
                    original_filename TEXT,
                    stored_filename TEXT,
                    file_path TEXT,
                    file_mime_type TEXT,
                    file_size BIGINT,
                    storage_backend TEXT DEFAULT 'local',
                    object_key TEXT,
                    file_url TEXT,
                    file_hash TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
        else:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS corpus_submissions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    submitter_name TEXT,
                    submitter_email TEXT,
                    title TEXT NOT NULL,
                    source TEXT,
                    category TEXT NOT NULL,
                    genre TEXT,
                    language TEXT,
                    modality TEXT NOT NULL,
                    text_content TEXT,
                    original_filename TEXT,
                    stored_filename TEXT,
                    file_path TEXT,
                    file_mime_type TEXT,
                    file_size INTEGER,
                    storage_backend TEXT DEFAULT 'local',
                    object_key TEXT,
                    file_url TEXT,
                    file_hash TEXT,
                    status TEXT DEFAULT 'pending',
                    admin_note TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    reviewed_at TIMESTAMP,
                    reviewed_by TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS multimodal_entries (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    submission_id INTEGER UNIQUE,
                    title TEXT NOT NULL,
                    source TEXT,
                    category TEXT,
                    genre TEXT,
                    language TEXT,
                    modality TEXT NOT NULL,
                    text_content TEXT,
                    original_filename TEXT,
                    stored_filename TEXT,
                    file_path TEXT,
                    file_mime_type TEXT,
                    file_size INTEGER,
                    storage_backend TEXT DEFAULT 'local',
                    object_key TEXT,
                    file_url TEXT,
                    file_hash TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)
        ensure_storage_metadata_columns(conn)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_submissions_status ON corpus_submissions (status)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON corpus_submissions (created_at)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_multimodal_submission_id ON multimodal_entries (submission_id)")
        conn.commit()
    finally:
        close_connection(conn)


def load_all_data():
    conn = get_db_connection()
    try:
        return fetch_all_dicts(conn.execute("SELECT * FROM corpus_entries ORDER BY id DESC"))
    finally:
        close_connection(conn)


def get_filter_options():
    start = time.perf_counter()
    conn = timed_connection("get_filter_options")
    try:
        sources = [
            row["source"]
            for row in conn.execute("""
                SELECT DISTINCT source
                FROM corpus_entries
                WHERE source IS NOT NULL AND TRIM(source) != ''
                ORDER BY source
            """).fetchall()
        ]
        years = [
            row["year"]
            for row in conn.execute("""
                SELECT DISTINCT year
                FROM corpus_entries
                WHERE year IS NOT NULL
                ORDER BY year DESC
            """).fetchall()
        ]
        return sources, years
    finally:
        close_connection(conn)
        if is_postgres():
            timing_log("get_filter_options.total", start)


def escape_like(value):
    return value.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")


def build_sqlite_filter_clauses(source="", year="", category="", table_name=""):
    marker = placeholder()
    where_clauses = []
    params = []
    prefix = f"{table_name}." if table_name else ""
    if source:
        where_clauses.append(f"{prefix}source = {marker}")
        params.append(source)
    if year:
        try:
            where_clauses.append(f"{prefix}year = {marker}")
            params.append(int(year))
        except ValueError:
            pass
    if category:
        where_clauses.append(f"{prefix}category = {marker}")
        params.append(category)
    return where_clauses, params


def build_postgres_search_where(keyword="", source="", year="", category=""):
    where_clauses = []
    params = []
    if keyword:
        like_value = f"%{keyword}%"
        where_clauses.append(f"{POSTGRES_SEARCH_TEXT_FIELD} ILIKE %s")
        params.append(like_value)
    if source:
        where_clauses.append("source = %s")
        params.append(source)
    if year:
        try:
            where_clauses.append("year = %s")
            params.append(int(year))
        except ValueError:
            pass
    if category:
        where_clauses.append("category = %s")
        params.append(category)
    where_sql = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""
    return where_sql, params


def build_search_where(keyword="", source="", year="", category=""):
    if is_postgres():
        return build_postgres_search_where(keyword, source, year, category)
    where_clauses = []
    params = []
    if keyword:
        where_clauses.append("content LIKE ? ESCAPE '\\'")
        params.append(f"%{escape_like(keyword)}%")
    filter_clauses, filter_params = build_sqlite_filter_clauses(source, year, category)
    where_clauses.extend(filter_clauses)
    params.extend(filter_params)
    where_sql = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""
    return where_sql, params


def build_postgres_legacy_search_where(keyword="", source="", year="", category=""):
    where_clauses = []
    params = []
    if keyword:
        like_value = f"%{keyword}%"
        search_parts = [f"{field} ILIKE %s" for field in POSTGRES_SEARCH_FIELDS]
        where_clauses.append(f"({' OR '.join(search_parts)})")
        params.extend([like_value] * len(POSTGRES_SEARCH_FIELDS))
    if source:
        where_clauses.append("source = %s")
        params.append(source)
    if year:
        try:
            where_clauses.append("year = %s")
            params.append(int(year))
        except ValueError:
            pass
    if category:
        where_clauses.append("category = %s")
        params.append(category)
    where_sql = f"WHERE {' AND '.join(where_clauses)}" if where_clauses else ""
    return where_sql, params


def should_use_fts_match(keyword):
    compact = re.sub(r"\s+", "", keyword or "")
    return len(compact) >= 3


def escape_fts_keyword(value):
    return (value or "").replace('"', '""').strip()


def build_fts_match_query(keyword):
    safe_keyword = escape_fts_keyword(keyword)
    if not safe_keyword:
        return ""
    return f'"{safe_keyword}"'


def has_fts_table():
    if is_postgres():
        return False
    conn = get_db_connection()
    try:
        row = conn.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",
            (FTS_TABLE,),
        ).fetchone()
        return row is not None
    finally:
        close_connection(conn)


def get_active_search_backend(configured_backend="fts"):
    if is_postgres():
        return "postgres"
    backend = configured_backend if configured_backend in {"like", "fts"} else "like"
    if backend == "fts" and has_fts_table():
        return "fts"
    return "like"


def count_search_results(keyword="", source="", year="", category=""):
    start = time.perf_counter()
    where_sql, params = build_search_where(keyword, source, year, category)
    conn = timed_connection("count_search_results")
    try:
        try:
            row = fetch_one_dict(conn.execute(f"SELECT COUNT(*) AS total FROM corpus_entries {where_sql}", params))
        except Exception as exc:
            if not is_missing_search_text_error(exc):
                raise
            conn.rollback()
            legacy_where_sql, legacy_params = build_postgres_legacy_search_where(keyword, source, year, category)
            row = fetch_one_dict(conn.execute(f"SELECT COUNT(*) AS total FROM corpus_entries {legacy_where_sql}", legacy_params))
        return row["total"]
    finally:
        close_connection(conn)
        if is_postgres():
            timing_log("count_search_results.total", start, keyword_len=len(keyword or ""), has_filter=bool(source or year or category))


def count_search_results_fts(keyword="", source="", year="", category=""):
    if is_postgres() or not should_use_fts_match(keyword):
        return count_search_results(keyword, source, year, category)
    match_query = build_fts_match_query(keyword)
    if not match_query:
        return count_search_results(keyword, source, year, category)
    filter_clauses, filter_params = build_sqlite_filter_clauses(source, year, category, "corpus_entries")
    where_clauses = [f"{FTS_TABLE} MATCH ?"]
    where_clauses.extend(filter_clauses)
    params = [match_query, *filter_params]
    where_sql = f"WHERE {' AND '.join(where_clauses)}"
    conn = get_db_connection()
    try:
        row = fetch_one_dict(conn.execute(
            f"""
            SELECT COUNT(*) AS total
            FROM {FTS_TABLE}
            JOIN corpus_entries ON {FTS_TABLE}.rowid = corpus_entries.id
            {where_sql}
            """,
            params,
        ))
        return row["total"]
    finally:
        close_connection(conn)


def query_search_page(keyword="", source="", year="", category="", limit=50, offset=0):
    start = time.perf_counter()
    where_sql, params = build_search_where(keyword, source, year, category)
    marker = placeholder()
    conn = timed_connection("query_search_page")
    try:
        try:
            rows = conn.execute(
                f"""
                SELECT *
                FROM corpus_entries
                {where_sql}
                ORDER BY id DESC
                LIMIT {marker} OFFSET {marker}
                """,
                [*params, limit, offset],
            ).fetchall()
        except Exception as exc:
            if not is_missing_search_text_error(exc):
                raise
            conn.rollback()
            legacy_where_sql, legacy_params = build_postgres_legacy_search_where(keyword, source, year, category)
            rows = conn.execute(
                f"""
                SELECT *
                FROM corpus_entries
                {legacy_where_sql}
                ORDER BY id DESC
                LIMIT {marker} OFFSET {marker}
                """,
                [*legacy_params, limit, offset],
            ).fetchall()
        return [row_to_dict(row) for row in rows]
    finally:
        close_connection(conn)
        if is_postgres():
            timing_log("query_search_page.total", start, keyword_len=len(keyword or ""), limit=limit, offset=offset)


def query_search_page_fts(keyword="", source="", year="", category="", limit=50, offset=0):
    if is_postgres() or not should_use_fts_match(keyword):
        return query_search_page(keyword, source, year, category, limit=limit, offset=offset)
    match_query = build_fts_match_query(keyword)
    if not match_query:
        return query_search_page(keyword, source, year, category, limit=limit, offset=offset)
    filter_clauses, filter_params = build_sqlite_filter_clauses(source, year, category, "corpus_entries")
    where_clauses = [f"{FTS_TABLE} MATCH ?"]
    where_clauses.extend(filter_clauses)
    params = [match_query, *filter_params, limit, offset]
    where_sql = f"WHERE {' AND '.join(where_clauses)}"
    conn = get_db_connection()
    try:
        rows = conn.execute(
            f"""
            SELECT corpus_entries.*
            FROM {FTS_TABLE}
            JOIN corpus_entries ON {FTS_TABLE}.rowid = corpus_entries.id
            {where_sql}
            ORDER BY corpus_entries.id DESC
            LIMIT ? OFFSET ?
            """,
            params,
        ).fetchall()
        return [row_to_dict(row) for row in rows]
    finally:
        close_connection(conn)


def has_extended_schema(conn):
    if is_postgres():
        return True
    columns = {row["name"] for row in conn.execute("PRAGMA table_info(corpus_entries)").fetchall()}
    return {"dataset_name", "created_at", "import_batch", "content_hash"}.issubset(columns)


def insert_entry(title, content, source, year, category):
    conn = get_db_connection()
    try:
        if is_postgres():
            conn.execute(
                """
                INSERT INTO corpus_entries (
                    title, content, source, year, category,
                    dataset_name, created_at, import_batch, content_hash, search_text
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    title,
                    content,
                    source,
                    year,
                    category,
                    "admin_manual",
                    utc_timestamp(),
                    "admin_manual",
                    compute_content_hash(content),
                    build_search_text(title, content),
                ),
            )
        elif has_extended_schema(conn):
            conn.execute(
                f"""
                INSERT INTO corpus_entries (
                    title, content, source, year, category,
                    dataset_name, created_at, import_batch, content_hash
                )
                VALUES ({placeholder()}, {placeholder()}, {placeholder()}, {placeholder()}, {placeholder()},
                        {placeholder()}, {placeholder()}, {placeholder()}, {placeholder()})
                """,
                (
                    title,
                    content,
                    source,
                    year,
                    category,
                    category or source,
                    utc_timestamp(),
                    "admin_manual",
                    compute_content_hash(content),
                ),
            )
        else:
            conn.execute(
                "INSERT INTO corpus_entries (title, content, source, year, category) VALUES (?, ?, ?, ?, ?)",
                (title, content, source, year, category),
            )
        conn.commit()
    finally:
        close_connection(conn)


def insert_approved_text_submission(conn, submission):
    content = (submission["text_content"] or "").strip()
    if not content:
        raise ValueError("文本类投稿必须包含文本内容。")
    if is_postgres():
        conn.execute(
            """
            INSERT INTO corpus_entries (
                title, content, source, year, category,
                dataset_name, created_at, import_batch, content_hash, search_text
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                submission["title"],
                content,
                submission["source"] or submission["category"],
                None,
                submission["category"],
                "public_submission",
                utc_timestamp(),
                "public_submission",
                compute_content_hash(content),
                build_search_text(submission["title"], content),
            ),
        )
    elif has_extended_schema(conn):
        conn.execute(
            f"""
            INSERT INTO corpus_entries (
                title, content, source, year, category,
                dataset_name, created_at, import_batch, content_hash
            )
            VALUES ({placeholder()}, {placeholder()}, {placeholder()}, {placeholder()}, {placeholder()},
                    {placeholder()}, {placeholder()}, {placeholder()}, {placeholder()})
            """,
            (
                submission["title"],
                content,
                submission["source"] or submission["category"],
                None,
                submission["category"],
                submission["category"] or submission["source"],
                utc_timestamp(),
                "public_submission",
                compute_content_hash(content),
            ),
        )
    else:
        conn.execute(
            "INSERT INTO corpus_entries (title, content, source, year, category) VALUES (?, ?, ?, ?, ?)",
            (
                submission["title"],
                content,
                submission["source"] or submission["category"],
                None,
                submission["category"],
            ),
        )


def insert_multimodal_entry(conn, submission):
    include_storage_metadata = has_storage_metadata_schema(conn, "multimodal_entries")
    conflict_sql = "ON CONFLICT (submission_id) DO NOTHING" if is_postgres() else "OR IGNORE"
    if include_storage_metadata and is_postgres():
        sql = """
            INSERT INTO multimodal_entries (
                submission_id, title, source, category, genre, language, modality,
                text_content, original_filename, stored_filename, file_path,
                file_mime_type, file_size, storage_backend, object_key, file_url, file_hash
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (submission_id) DO NOTHING
        """
    elif include_storage_metadata:
        sql = """
            INSERT OR IGNORE INTO multimodal_entries (
                submission_id, title, source, category, genre, language, modality,
                text_content, original_filename, stored_filename, file_path,
                file_mime_type, file_size, storage_backend, object_key, file_url, file_hash
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
    else:
        sql = """
            INSERT OR IGNORE INTO multimodal_entries (
                submission_id, title, source, category, genre, language, modality,
                text_content, original_filename, stored_filename, file_path,
                file_mime_type, file_size
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
    values = [
        submission["id"],
        submission["title"],
        submission["source"],
        submission["category"],
        submission["genre"],
        submission["language"],
        submission["modality"],
        submission["text_content"],
        submission["original_filename"],
        submission["stored_filename"],
        submission["file_path"],
        submission["file_mime_type"],
        submission["file_size"],
    ]
    if include_storage_metadata:
        values.extend([
            submission.get("storage_backend") or "local",
            submission.get("object_key") or submission.get("stored_filename"),
            submission.get("file_url"),
            submission.get("file_hash"),
        ])
    conn.execute(sql, tuple(values))


insert_approved_multimodal_submission = insert_multimodal_entry


def create_submission(form_values, file_info=None):
    marker = placeholder()
    conn = get_db_connection()
    try:
        include_storage_metadata = has_storage_metadata_schema(conn, "corpus_submissions")
        if include_storage_metadata:
            columns = """
                submitter_name, submitter_email, title, source, category, genre,
                language, modality, text_content, original_filename, stored_filename,
                file_path, file_mime_type, file_size, storage_backend, object_key,
                file_url, file_hash, status
            """
            values_sql = f"""
                {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, {marker},
                {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, {marker},
                {marker}, {marker}, 'pending'
            """
            values = (
                form_values["submitter_name"],
                form_values["submitter_email"],
                form_values["title"],
                form_values["source"],
                form_values["category"],
                form_values["genre"],
                form_values["language"],
                form_values["modality"],
                form_values["text_content"],
                file_info["original_filename"] if file_info else None,
                file_info["stored_filename"] if file_info else None,
                file_info["file_path"] if file_info else None,
                file_info["file_mime_type"] if file_info else None,
                file_info["file_size"] if file_info else None,
                file_info.get("storage_backend", "local") if file_info else "local",
                file_info.get("object_key") if file_info else None,
                file_info.get("file_url") if file_info else None,
                file_info.get("file_hash") if file_info else None,
            )
        else:
            columns = """
                submitter_name, submitter_email, title, source, category, genre,
                language, modality, text_content, original_filename, stored_filename,
                file_path, file_mime_type, file_size, status
            """
            values_sql = f"""
                {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, {marker},
                {marker}, {marker}, {marker}, {marker}, {marker}, {marker}, 'pending'
            """
            values = (
                form_values["submitter_name"],
                form_values["submitter_email"],
                form_values["title"],
                form_values["source"],
                form_values["category"],
                form_values["genre"],
                form_values["language"],
                form_values["modality"],
                form_values["text_content"],
                file_info["original_filename"] if file_info else None,
                file_info["stored_filename"] if file_info else None,
                file_info["file_path"] if file_info else None,
                file_info["file_mime_type"] if file_info else None,
                file_info["file_size"] if file_info else None,
            )
        conn.execute(
            f"""
            INSERT INTO corpus_submissions ({columns})
            VALUES ({values_sql})
            """,
            values,
        )
        conn.commit()
    finally:
        close_connection(conn)


def list_submissions(status="pending"):
    marker = placeholder()
    conn = get_db_connection()
    try:
        if status == "all":
            rows = conn.execute("""
                SELECT *
                FROM corpus_submissions
                ORDER BY created_at DESC, id DESC
            """).fetchall()
        else:
            rows = conn.execute(
                f"""
                SELECT *
                FROM corpus_submissions
                WHERE status = {marker}
                ORDER BY created_at DESC, id DESC
                """,
                (status,),
            ).fetchall()
        return [row_to_dict(row) for row in rows]
    finally:
        close_connection(conn)


def get_submission_by_id(submission_id):
    conn = get_db_connection()
    try:
        row = conn.execute(
            f"SELECT * FROM corpus_submissions WHERE id = {placeholder()}",
            (submission_id,),
        ).fetchone()
        return row_to_dict(row)
    finally:
        close_connection(conn)


def approve_submission_record(submission_id, admin_note=""):
    marker = placeholder()
    conn = get_db_connection()
    submission = None
    try:
        submission = row_to_dict(conn.execute(
            f"SELECT * FROM corpus_submissions WHERE id = {marker}",
            (submission_id,),
        ).fetchone())
        if submission is None:
            return None, "missing"
        if submission["status"] == "approved":
            return submission, "already_approved"
        if submission["modality"] in {"text", "txt"} and not submission["stored_filename"]:
            insert_approved_text_submission(conn, submission)
        elif submission["modality"] in {"text", "txt"} and (submission["text_content"] or "").strip():
            insert_approved_text_submission(conn, submission)
        else:
            insert_multimodal_entry(conn, submission)
        conn.execute(
            f"""
            UPDATE corpus_submissions
            SET status = 'approved',
                admin_note = {marker},
                reviewed_at = CURRENT_TIMESTAMP,
                reviewed_by = {marker}
            WHERE id = {marker}
            """,
            (admin_note, "admin", submission_id),
        )
        conn.commit()
        return submission, "approved"
    except Exception:
        conn.rollback()
        raise
    finally:
        close_connection(conn)


def reject_submission_record(submission_id, admin_note=""):
    marker = placeholder()
    conn = get_db_connection()
    try:
        conn.execute(
            f"""
            UPDATE corpus_submissions
            SET status = 'rejected',
                admin_note = {marker},
                reviewed_at = CURRENT_TIMESTAMP,
                reviewed_by = {marker}
            WHERE id = {marker}
            """,
            (admin_note, "admin", submission_id),
        )
        conn.commit()
    finally:
        close_connection(conn)


def delete_submission_record(submission_id):
    marker = placeholder()
    conn = get_db_connection()
    try:
        submission = row_to_dict(conn.execute(
            f"SELECT * FROM corpus_submissions WHERE id = {marker}",
            (submission_id,),
        ).fetchone())
        if submission:
            conn.execute(f"DELETE FROM corpus_submissions WHERE id = {marker}", (submission_id,))
            conn.commit()
        return submission
    finally:
        close_connection(conn)
