CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS corpus_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    source TEXT NOT NULL,
    year INTEGER,
    category TEXT,
    dataset_name TEXT,
    created_at TIMESTAMP,
    import_batch TEXT,
    content_hash TEXT,
    source_url TEXT,
    crawl_source TEXT,
    crawl_date TEXT,
    license_note TEXT,
    audio_file TEXT,
    segment_text TEXT,
    current_segment TEXT,
    prev_segment TEXT,
    next_segment TEXT,
    start_time DOUBLE PRECISION,
    end_time DOUBLE PRECISION,
    speaker TEXT,
    conversation_id TEXT,
    segment_index INTEGER,
    search_text TEXT
);

CREATE TABLE IF NOT EXISTS corpus_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_name TEXT,
    submitter_email TEXT,
    title TEXT NOT NULL,
    source TEXT,
    category TEXT NOT NULL,
    genre TEXT,
    language TEXT,
    modality TEXT NOT NULL,
    text_content TEXT,
    original_filename TEXT,
    stored_filename TEXT,
    file_path TEXT,
    file_mime_type TEXT,
    file_size BIGINT,
    storage_backend TEXT DEFAULT 'local',
    object_key TEXT,
    file_url TEXT,
    file_hash TEXT,
    status TEXT DEFAULT 'pending',
    admin_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by TEXT
);

CREATE TABLE IF NOT EXISTS multimodal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT UNIQUE,
    title TEXT NOT NULL,
    source TEXT,
    category TEXT,
    genre TEXT,
    language TEXT,
    modality TEXT NOT NULL,
    text_content TEXT,
    original_filename TEXT,
    stored_filename TEXT,
    file_path TEXT,
    file_mime_type TEXT,
    file_size BIGINT,
    storage_backend TEXT DEFAULT 'local',
    object_key TEXT,
    file_url TEXT,
    file_hash TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE corpus_entries
    ADD COLUMN IF NOT EXISTS search_text TEXT,
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS crawl_source TEXT,
    ADD COLUMN IF NOT EXISTS crawl_date TEXT,
    ADD COLUMN IF NOT EXISTS license_note TEXT;

CREATE INDEX IF NOT EXISTS idx_corpus_category ON corpus_entries (category);
CREATE INDEX IF NOT EXISTS idx_corpus_source ON corpus_entries (source);
CREATE INDEX IF NOT EXISTS idx_corpus_year ON corpus_entries (year);
CREATE INDEX IF NOT EXISTS idx_corpus_dataset_name ON corpus_entries (dataset_name);
CREATE INDEX IF NOT EXISTS idx_corpus_conversation_segment ON corpus_entries (conversation_id, segment_index);
CREATE INDEX IF NOT EXISTS idx_corpus_content_hash ON corpus_entries (content_hash);
CREATE INDEX IF NOT EXISTS idx_corpus_source_url ON corpus_entries (source_url);
CREATE INDEX IF NOT EXISTS idx_corpus_crawl_source ON corpus_entries (crawl_source);
CREATE INDEX IF NOT EXISTS idx_corpus_crawl_date ON corpus_entries (crawl_date);
CREATE INDEX IF NOT EXISTS idx_corpus_audio_file ON corpus_entries (audio_file);

ALTER TABLE corpus_submissions
    ADD COLUMN IF NOT EXISTS storage_backend TEXT DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS object_key TEXT,
    ADD COLUMN IF NOT EXISTS file_url TEXT,
    ADD COLUMN IF NOT EXISTS file_hash TEXT;

ALTER TABLE multimodal_entries
    ADD COLUMN IF NOT EXISTS storage_backend TEXT DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS object_key TEXT,
    ADD COLUMN IF NOT EXISTS file_url TEXT,
    ADD COLUMN IF NOT EXISTS file_hash TEXT;

CREATE INDEX IF NOT EXISTS idx_submissions_status ON corpus_submissions (status);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON corpus_submissions (created_at);
CREATE INDEX IF NOT EXISTS idx_multimodal_submission_id ON multimodal_entries (submission_id);

-- Baseline PostgreSQL search can use ILIKE. These trigram indexes improve ILIKE
-- when pg_trgm is available; if the extension is unavailable, remove only these
-- GIN index statements and the application can still fall back to plain ILIKE.
CREATE INDEX IF NOT EXISTS idx_corpus_title_trgm
    ON corpus_entries USING GIN (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_content_trgm
    ON corpus_entries USING GIN (content gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_current_segment_trgm
    ON corpus_entries USING GIN (current_segment gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_speaker_trgm
    ON corpus_entries USING GIN (speaker gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_search_text_trgm
    ON corpus_entries USING GIN (search_text gin_trgm_ops);
