CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS corpus_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    source TEXT NOT NULL,
    year INTEGER,
    category TEXT,
    dataset_name TEXT,
    created_at TIMESTAMP,
    import_batch TEXT,
    content_hash TEXT,
    source_url TEXT,
    crawl_source TEXT,
    crawl_date TEXT,
    license_note TEXT,
    audio_file TEXT,
    segment_text TEXT,
    current_segment TEXT,
    prev_segment TEXT,
    next_segment TEXT,
    start_time DOUBLE PRECISION,
    end_time DOUBLE PRECISION,
    speaker TEXT,
    conversation_id TEXT,
    segment_index INTEGER,
    search_text TEXT
);

CREATE TABLE IF NOT EXISTS corpus_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitter_name TEXT,
    submitter_email TEXT,
    title TEXT NOT NULL,
    source TEXT,
    category TEXT NOT NULL,
    genre TEXT,
    language TEXT,
    modality TEXT NOT NULL,
    text_content TEXT,
    original_filename TEXT,
    stored_filename TEXT,
    file_path TEXT,
    file_mime_type TEXT,
    file_size BIGINT,
    storage_backend TEXT DEFAULT 'local',
    object_key TEXT,
    file_url TEXT,
    file_hash TEXT,
    status TEXT DEFAULT 'pending',
    admin_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by TEXT
);

CREATE TABLE IF NOT EXISTS multimodal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT UNIQUE,
    title TEXT NOT NULL,
    source TEXT,
    category TEXT,
    genre TEXT,
    language TEXT,
    modality TEXT NOT NULL,
    text_content TEXT,
    original_filename TEXT,
    stored_filename TEXT,
    file_path TEXT,
    file_mime_type TEXT,
    file_size BIGINT,
    storage_backend TEXT DEFAULT 'local',
    object_key TEXT,
    file_url TEXT,
    file_hash TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dialogue_turns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    turn_index INTEGER NOT NULL,
    speaker_label TEXT,
    turn_text TEXT NOT NULL,
    source TEXT,
    category TEXT,
    dataset_name TEXT,
    conversation_key TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS corpus_stats (
    stat_key TEXT PRIMARY KEY,
    stat_value TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_visitors (
    visitor_hash VARCHAR(64) PRIMARY KEY,
    first_seen_epoch BIGINT NOT NULL,
    last_seen_epoch BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS site_visitor_daily (
    day_key VARCHAR(10) NOT NULL,
    visitor_hash VARCHAR(64) NOT NULL,
    first_seen_epoch BIGINT NOT NULL,
    last_seen_epoch BIGINT NOT NULL,
    PRIMARY KEY (day_key, visitor_hash)
);

CREATE TABLE IF NOT EXISTS site_visit_snapshots (
    bucket_epoch BIGINT PRIMARY KEY,
    online_visitors INTEGER NOT NULL,
    peak_online_visitors INTEGER NOT NULL,
    total_visitors BIGINT NOT NULL,
    daily_visitors BIGINT NOT NULL,
    recorded_at_epoch BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS site_ip_activity (
    ip_address VARCHAR(45) NOT NULL,
    bucket_epoch BIGINT NOT NULL,
    first_seen_epoch BIGINT NOT NULL,
    last_seen_epoch BIGINT NOT NULL,
    request_count BIGINT NOT NULL,
    blocked_count BIGINT NOT NULL DEFAULT 0,
    last_path VARCHAR(255),
    last_method VARCHAR(12),
    last_status INTEGER,
    PRIMARY KEY (ip_address, bucket_epoch)
);

CREATE TABLE IF NOT EXISTS site_blocked_ips (
    ip_address VARCHAR(45) PRIMARY KEY,
    reason TEXT,
    blocked_at_epoch BIGINT NOT NULL,
    blocked_by VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS dialogue_pairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_a_id BIGINT NOT NULL,
    turn_b_id BIGINT NOT NULL,
    entry_id BIGINT NOT NULL,
    conversation_key TEXT NOT NULL,
    turn_index_a INTEGER NOT NULL,
    turn_index_b INTEGER NOT NULL,
    speaker_a TEXT,
    speaker_b TEXT,
    text_a TEXT NOT NULL,
    text_b TEXT NOT NULL,
    source TEXT,
    category TEXT,
    dataset_name TEXT,
    shared_terms TEXT,
    markers TEXT,
    has_lexical_echo INTEGER DEFAULT 0,
    has_pattern_reuse INTEGER DEFAULT 0,
    has_question_response INTEGER DEFAULT 0,
    has_negation_turn INTEGER DEFAULT 0,
    has_repair_repetition INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE corpus_entries
    ADD COLUMN IF NOT EXISTS search_text TEXT,
    ADD COLUMN IF NOT EXISTS source_url TEXT,
    ADD COLUMN IF NOT EXISTS crawl_source TEXT,
    ADD COLUMN IF NOT EXISTS crawl_date TEXT,
    ADD COLUMN IF NOT EXISTS license_note TEXT;

CREATE INDEX IF NOT EXISTS idx_corpus_category ON corpus_entries (category);
CREATE INDEX IF NOT EXISTS idx_corpus_source ON corpus_entries (source);
CREATE INDEX IF NOT EXISTS idx_corpus_year ON corpus_entries (year);
CREATE INDEX IF NOT EXISTS idx_corpus_dataset_name ON corpus_entries (dataset_name);
CREATE INDEX IF NOT EXISTS idx_corpus_conversation_segment ON corpus_entries (conversation_id, segment_index);
CREATE INDEX IF NOT EXISTS idx_corpus_content_hash ON corpus_entries (content_hash);
CREATE INDEX IF NOT EXISTS idx_corpus_source_url ON corpus_entries (source_url);
CREATE INDEX IF NOT EXISTS idx_corpus_crawl_source ON corpus_entries (crawl_source);
CREATE INDEX IF NOT EXISTS idx_corpus_crawl_date ON corpus_entries (crawl_date);
CREATE INDEX IF NOT EXISTS idx_corpus_audio_file ON corpus_entries (audio_file);
CREATE INDEX IF NOT EXISTS idx_site_visitors_last_seen ON site_visitors (last_seen_epoch);
CREATE INDEX IF NOT EXISTS idx_site_visitor_daily_day ON site_visitor_daily (day_key);
CREATE INDEX IF NOT EXISTS idx_site_visit_snapshots_bucket ON site_visit_snapshots (bucket_epoch);
CREATE INDEX IF NOT EXISTS idx_site_ip_activity_last_seen ON site_ip_activity (last_seen_epoch);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_entry ON dialogue_turns (entry_id);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_entry_id ON dialogue_turns (entry_id);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_conversation ON dialogue_turns (conversation_key, turn_index);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_conversation_turn ON dialogue_turns (conversation_key, turn_index);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_source ON dialogue_turns (source);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_category ON dialogue_turns (category);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_source_category_id ON dialogue_turns (source, category, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_turns_turn_text_trgm
    ON dialogue_turns USING GIN (turn_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_a ON dialogue_pairs(turn_a_id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_b ON dialogue_pairs(turn_b_id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_entry ON dialogue_pairs(entry_id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_source_category_id ON dialogue_pairs(source, category, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_lexical ON dialogue_pairs(has_lexical_echo, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_pattern ON dialogue_pairs(has_pattern_reuse, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_question ON dialogue_pairs(has_question_response, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_negation ON dialogue_pairs(has_negation_turn, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_repair ON dialogue_pairs(has_repair_repetition, id);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_text_a_trgm
    ON dialogue_pairs USING GIN (text_a gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_dialogue_pairs_text_b_trgm
    ON dialogue_pairs USING GIN (text_b gin_trgm_ops);

ALTER TABLE corpus_submissions
    ADD COLUMN IF NOT EXISTS storage_backend TEXT DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS object_key TEXT,
    ADD COLUMN IF NOT EXISTS file_url TEXT,
    ADD COLUMN IF NOT EXISTS file_hash TEXT;

ALTER TABLE multimodal_entries
    ADD COLUMN IF NOT EXISTS storage_backend TEXT DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS object_key TEXT,
    ADD COLUMN IF NOT EXISTS file_url TEXT,
    ADD COLUMN IF NOT EXISTS file_hash TEXT;

CREATE INDEX IF NOT EXISTS idx_submissions_status ON corpus_submissions (status);
CREATE INDEX IF NOT EXISTS idx_submissions_created_at ON corpus_submissions (created_at);
CREATE INDEX IF NOT EXISTS idx_multimodal_submission_id ON multimodal_entries (submission_id);

-- Baseline PostgreSQL search can use ILIKE. These trigram indexes improve ILIKE
-- when pg_trgm is available; if the extension is unavailable, remove only these
-- GIN index statements and the application can still fall back to plain ILIKE.
CREATE INDEX IF NOT EXISTS idx_corpus_title_trgm
    ON corpus_entries USING GIN (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_content_trgm
    ON corpus_entries USING GIN (content gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_current_segment_trgm
    ON corpus_entries USING GIN (current_segment gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_speaker_trgm
    ON corpus_entries USING GIN (speaker gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_corpus_search_text_trgm
    ON corpus_entries USING GIN (search_text gin_trgm_ops);
